### ISSUE TITLE
lazy regressor not working 

### ISSUE THREAD

**Issue by guhan93** [shankarpandala/lazypredict#102]
**Describe the bug**
the lazy regressor is not working 

**To Reproduce**
1. run the lazy regressor code
2.you'll see there is no output displayed only the learning rates are available 
3. no r-square value displayed
5. there is a problem in the stackregressor
4. see an error

ran on google colab

![image](https://user-images.githubusercontent.com/47147736/87074652-cb213980-c23c-11ea-89e3-eb64041858c4.png)

**Comment by shankarpandala** [comment]
I don't see you printing models 
Just type models and see if it prints the table

Stacked regressor is not available yet but it won't stop you from getting results of other algorithms

**Comment by guhan93** [comment]
okay thanks, it's working
