### ISSUE TITLE
Very slow in running a classification algorithm - how to make it faster?

### ISSUE THREAD

**Issue by vaishalisvp** [shankarpandala/lazypredict#110]
* Lazy Predict version: lazypredict-0.2.7
* Python version: 3
* Operating System: Windows

### Description

I am trying to run lazypredict code for a classification use-case and it has been stuck at 3% for over 2 hours. the data size is around 15,000 observations. Any way to speed up the code? Thanks!

### What I Did

```
from lazypredict.Supervised import LazyClassifier
from sklearn.model_selection import train_test_split
import numpy as np

X=data['text']
y=data['category_id']
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=.3,random_state =1)
clf = LazyClassifier(verbose=0,ignore_warnings=True, custom_metric=None)
models,predictions = clf.fit(np.array(X_train), np.array(X_test), np.array(y_train), np.array(y_test))
models
```
![image](https://user-images.githubusercontent.com/31619885/87660277-19fc3100-c75f-11ea-9104-6d4793b12bf0.png)

**Comment by ramanathan831** [comment]
Hey, what was your Dataset set and was your processed killed after sometime?

**Comment by shankarpandala** [comment]
Let me know what it shows with verbose=1 and ignore_warnings=false

Also can you show me sample data? It looks like you are using text data which this library is not yet meant for. Text classification is not yet implemented.

**Comment by vaishalisvp** [comment]
hi yes, I was using text data. thanks for clarifying!

**Comment by shankarpandala** [comment]
@vaishalisvp Still thanks for raising the issue. I will try incorporate text classification also in future releases.

**Comment by jdvala** [comment]
Hi @vaishalisvp I have created a package inspired by lazypredict for text classification, please check it out, comments and suggestions are welcome. https://github.com/jdvala/lazytext

**Comment by Eyamech** [comment]
Hey, 
I faced also the same problem :(
I got this:Unable to load extension: pydevd_plugins.extensions.types.pydevd_plugin_pandas_types
Can anyone help ? Thank you guys :D
