### ISSUE TITLE
Choose specific subset of algorithms

### ISSUE THREAD

**Issue by mvpalheta** [shankarpandala/lazypredict#114]
How to i choose a specific subset of algorithms when run Lazypredict ??

**Comment by shankarpandala** [comment]
Currently there is no such option. Will try to implement in next release

**Comment by brendalf** [comment]
@mvpalheta, now there is a option to pass a list of specific estimators.

**Comment by brendalf** [comment]
@mvpalheta, now there is a option to pass a list of specific estimators.

Check the PR #319.
