### ISSUE TITLE
After pip installing lazypredict, import lazypredict doesn't work. Improvement in Documentation.

### ISSUE THREAD

**Issue by vidyap-xgboost** [shankarpandala/lazypredict#115]
![Screenshot from 2020-07-19 02-14-43](https://user-images.githubusercontent.com/65642130/87861666-ffe06f80-c965-11ea-98d5-86b5b53d10b1.png)

From the above picture, it is clear that `lazypredict` is successfully installed, however, if I try to access it, it says *No module named `lazypredict`*. Why?

Also `README.rst` doesn't mention the steps to install this package and directly jumps to **USAGE**. Does it mean that it should work without pre-installation?

`CONTRIBUTING.rst` explains how to install using `setup.py` but doesn't mention that one should install `requirements_dev.txt` which is essential when working on virtual environments.

Is it fine if I open a PR regarding Documentation?

**Comment by vidyap-xgboost** [comment]
[UPDATE]

```python
>>>import lazypredict
```
works only after following these steps on my environment (Ubuntu 18.04, python==3.6.9):

```python
$ git clone git@github.com:your_name_here/lazypredict.git
$ mkvirtualenv lazypredict
$ cd lazypredict/
$ python setup.py develop
$ pip3 install -r requirements_dev.txt
```
I added `$ pip3 install -r requirements_dev.txt` because when I ran the [example](https://pypi.org/project/lazypredict/) given in the docs, it asked me to install `numpy`. That should have been automatically installed when I ran `setup.py`, however, `requirements.txt` instruction was not given in `CONTRIBUTING.md`. Once I did that, everything ran smoothly.

**Comment by vidyap-xgboost** [comment]
[DOCUMENTATION]

In any example, for now let's take [Classification](https://github.com/shankarpandala/lazypredict#classification), the examples are written as if they're executed using a `.py` file. That's how I assumed because an interactive shell would include `>>>` in them. When I ran the `.py` file, it executed the program well, however, I did not see any output. Why? Because the original example, I am assuming here again, was run on an interactive python shell. That's when I could immediately see the results as shown in the [docs](https://pypi.org/project/lazypredict/). 

To see the output, the author should either explicitly mention that the examples should be run on an interactive shell or change the examples to accommodate the traditional `>>>` 3 arrows to indicate that those examples are running on an interactive shell.

Let me know if I am wrong anywhere. Happy to discuss.

**Comment by shankarpandala** [comment]
@vidyap-xgboost This is interesting. No one faced this this issue. 
can you create a new conda environment and try installing with pip instead of pip3 ?

Regarding numpy and other packages not getting installed with pip. I think that is how pip works. while conda install will check for every dependency and install them. As this library is not published in conda yet we cannot use conda.

But, let me check the possibility of installing dependencies while installing with pip

Regarding installation instructions,  They are available in the docs. You can see it here : https://lazypredict.readthedocs.io/en/latest/installation.html

I think cloning the repo and installing the requirements is not a good idea here as this is not a project but a library. 

You are always open to raise a PR.

**Comment by vidyap-xgboost** [comment]
> @vidyap-xgboost This is interesting. No one faced this this issue.
> can you create a new conda environment and try installing with pip instead of pip3 ?

**I will look into this.**

> Regarding numpy and other packages not getting installed with pip. I think that is how pip works. while conda install will check for every dependency and install them. As this library is not published in conda yet we cannot use conda.
> 
> But, let me check the possibility of installing dependencies while installing with pip

**Sure, thanks for the clarification.**

> Regarding installation instructions, They are available in the docs. You can see it here : https://lazypredict.readthedocs.io/en/latest/installation.html
> 
> I think cloning the repo and installing the requirements is not a good idea here as this is not a project but a library.
> 
> You are always open to raise a PR.

**I agree. I added the installation instruction directly on README assuming people would be looking for it. A direct link to the docs is already provided but beginners wouldn't know where to look for unless **Installation** is explicitly mentioned right in the GitHub README (if they come across this first).**

**Could you also answer this question as well?**

> [DOCUMENTATION]

> In any example, for now let's take Classification, the examples are written as if they're executed using a .py file. That's how I assumed because an interactive shell would include >>> in them. When I ran the .py file, it executed the program well, however, I did not see any output. Why? Because the original example, I am assuming here again, was run on an interactive python shell. That's when I could immediately see the results as shown in the docs.

> To see the output, the author should either explicitly mention that the examples should be run on an interactive shell or change the examples to accommodate the traditional >>> 3 arrows to indicate that those examples are running on an interactive shell.

> Let me know if I am wrong anywhere. Happy to discuss.

**Finally, thanks for the merge!**

**Comment by shankarpandala** [comment]
I see there is a issue in readme.
We need to print`models` variable to see the results. Try the same example again and just type models you will see the results.

**Comment by vidyap-xgboost** [comment]
> I see there is a issue in readme.
> We need to print`models` variable to see the results. Try the same example again and just type models you will see the results.

That would work. Without `print()`, it sent the wrong message to me.

**Comment by shankarpandala** [comment]
Yeah it's a bug in the documentation that needs to be fixed. I appreciate your time in raising all the issues this will improve the library. Thanks.

**Comment by vidyap-xgboost** [comment]
Happy to work on this library. I appreciate you starting this library as it is easier for prototyping before implementing complex models in Machine Learning. 👍
