### ISSUE TITLE
Any reason why text files are written in reST instead of Markdown?

### ISSUE THREAD

**Issue by vidyap-xgboost** [shankarpandala/lazypredict#116]
Is it a personal choice or is there any technical reason where reST is better than Markdown? Asking this only because I rarely .rst file extensions.

**Comment by shankarpandala** [comment]
> Is it a personal choice or is there any technical reason where reST is better than Markdown? Asking this only because I rarely .rst file extensions.

@vidyap-xgboost I would say both. Markdown is used for simple markup and manual markup. 
Here, I am using automatic documentation generation using sphinx. .rst is a good choice for this scenario.
You can read about when to use what here : https://eli.thegreenplace.net/2017/restructuredtext-vs-markdown-for-technical-documentation/

**Comment by vidyap-xgboost** [comment]
> > Is it a personal choice or is there any technical reason where reST is better than Markdown? Asking this only because I rarely .rst file extensions.
> 
> @vidyap-xgboost I would say both. Markdown is used for simple markup and manual markup.
> Here, I am using automatic documentation generation using sphinx. .rst is a good choice for this scenario.
> You can read about when to use what here : https://eli.thegreenplace.net/2017/restructuredtext-vs-markdown-for-technical-documentation/

It would be really nice to have instructions on how to contribute to text files using sphinx in `CONTRIBUTING.rst`. Thanks for the clarification.

**Comment by shankarpandala** [comment]
@vidyap-xgboost I am not expert in sphinx and there are many problems with documentation for this library. Will work on them and give you the instructions.

**Comment by vidyap-xgboost** [comment]
> @vidyap-xgboost I am not expert in sphinx and there are many problems with documentation for this library. Will work on them and give you the instructions.

Sure. I am closing this issue here as there is clarity now. Thanks.
