### ISSUE TITLE
custom_metric (regression)

### ISSUE THREAD

**Issue by michael135** [shankarpandala/lazypredict#122]
`Custom_metric` is used for results evalutaion only?

Or it's also used in each model as `loss` for optimization?

**Comment by shankarpandala** [comment]
@michael135 It's for evaluation only

**Comment by michael135** [comment]
@shankarpandala  Thank you.
Each method has is default `mean_squared_error` loss for optimization?
Or it has its default loss, which was defined in sklearn?
Is there any option to define parameters, for some of the models?

**Comment by shankarpandala** [comment]
@michael135 All the model parameters are default.

**Comment by michael135** [comment]
Got it. Thank you.
