### ISSUE TITLE
Error - Stacking Regressor

### ISSUE THREAD

**Issue by byrnesy** [shankarpandala/lazypredict#223]
Hi,

I have copied the sample code for the regression comparison (Boston dataset).

It starts running and then stops with the following error message

StackingRegressor model failed to execute
__init__() missing 1 required positional argument: 'estimators'

Context
I am using sklearn = '0.23.1'
Using jupyter lab
Browser = Firefox

**Comment by erykml** [comment]
The reason for this error is that the library tries to fit the `StackingRegressor` without actually passing in any base regressors, which logically will not work. What you can do is clone the code, remove `StackingRegressor` from the list of regressors, and install the library from your local code. Hope this helps :) 

On a side note, this seems like an uncommitted change by the author, as in the example's results you do not see `StackingRegressor` in the list of regressors :)

**Comment by erykml** [comment]
Alternatively, set `ignore_warnings` to `True` and it will also run.
