### ISSUE TITLE
ModuleNotFoundError for lazypredict '0.2.7' and sklearn version: '0.24.0'

### ISSUE THREAD

**Issue by erikjamesmason** [shankarpandala/lazypredict#303]
**Describe the bug**

when using `from lazypredict.Supervised import LazyClassifier` in jupyter notebook:

```
--------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-778-0601eec82da4> in <module>
----> 1 from lazypredict.Supervised import LazyClassifier

~\AppData\Local\Continuum\anaconda3\lib\site-packages\lazypredict\Supervised.py in <module>
     14 from sklearn.preprocessing import StandardScaler, OneHotEncoder
     15 from sklearn.compose import ColumnTransformer
---> 16 from sklearn.utils.testing import all_estimators
     17 from sklearn.base import RegressorMixin
     18 from sklearn.base import ClassifierMixin

ModuleNotFoundError: No module named 'sklearn.utils.testing' 
```

**Versions**
sklearn version: '0.24.0'
Jupyter: 
jupyter core     : 4.6.3
jupyter-notebook : 6.1.1
qtconsole        : 4.7.7
ipython          : 7.19.0
ipykernel        : 5.3.4
jupyter client   : 6.1.7
jupyter lab      : 2.2.6
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 5.0.8
traitlets        : 4.3.3

**Expected behavior**
Expected Lazyclassifier to import, not have modulenotfound error - I have noticed that  sklearn.utils.testing doesn't seem have to testing listed for all_estimators, but rather just  sklearn.utils

Note: this is my first time opening an issue, if i can be more clear or helpful, please indicate how and i will be obliged to do so.

**Comment by shankarpandala** [comment]
Thanks for raising the issue. 
Please use sklearn 0.23.1 while using 0.2.7 version of lazy predict
In the next version of lazypredict I will update it to sklearn 0.24

**Comment by egligbe** [comment]
When will we get the next version to support current sklearn?
