### ISSUE TITLE
AttributeError: module 'lightgbm' has no attribute 'LGBMRegressor'

### ISSUE THREAD

**Issue by zyjcs** [shankarpandala/lazypredict#315]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-9-306802b0b17a> in <module>
----> 1 from lazypredict.Supervised import LazyClassifier, LazyRegressor
      2 from sklearn.model_selection import train_test_split
      3 from sklearn import datasets
      4 from lightgbm import *

~/opt/anaconda3/lib/python3.7/site-packages/lazypredict/Supervised.py in <module>
     77 
     78 REGRESSORS.append(('XGBRegressor', xgboost.XGBRegressor))
---> 79 REGRESSORS.append(('LGBMRegressor',lightgbm.LGBMRegressor))
     80 # REGRESSORS.append(('CatBoostRegressor',catboost.CatBoostRegressor))
     81 

AttributeError: module 'lightgbm' has no attribute 'LGBMRegressor'

------
MacOs 10.15.7
lightgbm 3.1.1
lazypredict       0.2.7

it show this error  why ?

**Comment by shyamcody** [comment]
[Is this a relevant answer](https://stackoverflow.com/questions/55312601/attribute-error-module-lightgbm-has-no-attribute-lgbmclassifier-and-datas) for you? is it possible that your script name is lightgbm.py. That ends up creating this issue. Check for example [this issue](https://github.com/microsoft/LightGBM/issues/706) as well where the solution is again same. If your script name is lightgbm.py then change it and should see no further confusion.

**Comment by brendalf** [comment]
Hi @zyjcs, the @shyamcody answer solved your problem?

**Comment by zyjcs** [comment]
> Hi @zyjcs, the @shyamcody answer solved your problem? Please, let us know

It's ok ~  Thank you very much. You do a great  jobs.
