### ISSUE TITLE
scipy version

### ISSUE THREAD

**Issue by hrsht-13** [shankarpandala/lazypredict#329]
ERROR: Could not find a version that satisfies the requirement scipy==1.6.0 (from lazypredict) (from versions: 0.8.0, 0.9.0, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.17.0, 0.17.1, 0.18.0rc2, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 1.0.0b1, 1.0.0rc1, 1.0.0rc2, 1.0.0, 1.0.1, 1.1.0rc1, 1.1.0, 1.2.0rc1, 1.2.0rc2, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.3.0rc1, 1.3.0rc2, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0rc1, 1.4.0rc2, 1.4.0, 1.4.1, 1.5.0rc1, 1.5.0rc2, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4)
ERROR: No matching distribution found for scipy==1.6.0 (from lazypredict)

**Comment by shyamcody** [comment]
@brendalf I am also facing same issue. Can we turn just 1.6.0 to more than equal to 1.6.0?

**Comment by shankarpandala** [comment]
I am not seeing this issue. I am able to install without any issues

**Comment by shyamcody** [comment]
I faced it when I tried to download in colab. Not sure how to give environment details for colab.

**Comment by filipre** [comment]
I "fixed" this by using 
```
pip install lazypredict==0.2.7
```

**Comment by shyamcody** [comment]
yeah that works! so then clearly the problem is with the latest version

**Comment by shankarpandala** [comment]
@brendalf Any idea why this is failing?

It worked in my laptop but it failed in colab.

**Comment by hrsht-13** [comment]
> I "fixed" this by using
> 
> ```
> pip install lazypredict==0.2.7
> ```
@filipre  Thank you, it worked.

**Comment by brendalf** [comment]
Hi everyone, sorry for the late reply.

The error is happening in which specific version? Before v0.2.7?

**Comment by brendalf** [comment]
I guess we can indeed replace `scipy==1.6.0` with `scipy>=1.6.0`, as you suggested @shyambhu123.
My only concern is about compatibility and depreceated functions. Perhaps we should start building some coverage tests for the library, what do you guys think?

**Comment by filipre** [comment]
Can someone explain the error message? Why does the package think that scipy 1.6. is not valid? Where does this list of versions come from? Why does it stop at 1.5.4? I've got similar errors from other packages and never figured out the root cause.

```
ERROR: Could not find a version that satisfies the requirement scipy==1.6.0 (from lazypredict) (from versions: 0.8.0, 0.9.0, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.17.0, 0.17.1, 0.18.0rc2, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 1.0.0b1, 1.0.0rc1, 1.0.0rc2, 1.0.0, 1.0.1, 1.1.0rc1, 1.1.0, 1.2.0rc1, 1.2.0rc2, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.3.0rc1, 1.3.0rc2, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0rc1, 1.4.0rc2, 1.4.0, 1.4.1, 1.5.0rc1, 1.5.0rc2, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4)
ERROR: No matching distribution found for scipy==1.6.0 (from lazypredict)
```

**Comment by shankarpandala** [comment]
updated scipy to an older version 
I have verified and is working on colab.

**Comment by shankarpandala** [comment]
> I guess we can indeed replace `scipy==1.6.0` with `scipy>=1.6.0`, as you suggested @shyambhu123.
> My only concern is about compatibility and depreceated functions. Perhaps we should build some coverage tests, what do you guys think?

Scipy>=1.6.0 also won't work as it is the latest version available now
I have downgraded scipy to 1.5.4

**Comment by shankarpandala** [comment]
@hrsht-13 @shyamcody @filipre 
Please use the latest version of lazypredict==0.2.9. This issue is fixed

**Comment by brendalf** [comment]
Excellent, @shankarpandala.
About the tests, I'll get done in the weekend, okay?

**Comment by shankarpandala** [comment]
Sure @brendalf

**Comment by aeyildirim** [comment]
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)

 get_ipython().system('pip install  lazypredict==0.2.9')


ModuleNotFoundError: No module named 'lazypredict'

I get this error about lazypredict. What can I do??
