### ISSUE TITLE
Intall ERROR: Cannot uninstall 'PyYAML'. 

### ISSUE THREAD

**Issue by JunMa11** [shankarpandala/lazypredict#332]
**Describe the bug**

Thanks for the great work.

I have the following errors when installing the latest lazypredict.

```
ERROR: astroid 2.3.1 requires typed-ast<1.5,>=1.4.0; implementation_name == "cpython" and python_version < "3.8", which is not installed.
ERROR: auto-sklearn 0.12.3 has requirement scikit-learn<0.25.0,>=0.24.0, but you'll have scikit-learn 0.23.1 which is incompatible.
ERROR: astroid 2.3.1 has requirement six==1.12, but you'll have six 1.15.0 which is incompatible.
Installing collected packages: scikit-learn, pytest, six, xgboost, pandas, tqdm, click, lightgbm, PyYAML, lazypredict
  Found existing installation: scikit-learn 0.24.1
    Uninstalling scikit-learn-0.24.1:
      Successfully uninstalled scikit-learn-0.24.1
  Found existing installation: pytest 5.2.1
    Uninstalling pytest-5.2.1:
      Successfully uninstalled pytest-5.2.1
  Found existing installation: six 1.12.0
    Uninstalling six-1.12.0:
      Successfully uninstalled six-1.12.0
  Found existing installation: pandas 1.2.2
    Uninstalling pandas-1.2.2:
      Successfully uninstalled pandas-1.2.2
  Found existing installation: tqdm 4.36.1
    Uninstalling tqdm-4.36.1:
      Successfully uninstalled tqdm-4.36.1
  Found existing installation: Click 7.0
    Uninstalling Click-7.0:
      Successfully uninstalled Click-7.0
  Found existing installation: PyYAML 5.1.2
ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

**To Reproduce**
1. `pip install lazypredict`

**Screenshots**

![image](https://user-images.githubusercontent.com/19947331/108652978-57e4e300-7500-11eb-9bdf-ec6061635bab.png)

![image](https://user-images.githubusercontent.com/19947331/108653019-6df2a380-7500-11eb-8699-b8f6e1697ef0.png)

**Desktop (please complete the following information):**

![image](https://user-images.githubusercontent.com/19947331/108653130-ae522180-7500-11eb-91c6-8cf6dadc446d.png)

Any help will be highly appreciated.

Best regards,
Jun

**Comment by nishnash54** [comment]
The `--ignore-installed` flag should do the trick.
Something like this `pip install --ignore-installed PyYAML`.
If not try one of the solutions from [here](https://stackoverflow.com/questions/49911550/how-to-upgrade-disutils-package-pyyaml)

**Comment by JunMa11** [comment]
Hi @nishnash54 ,

Thank you so much.

It works!

Best,
Jun
