### ISSUE TITLE
how to get per cases prediction results?

### ISSUE THREAD

**Issue by JunMa11** [shankarpandala/lazypredict#334]
**Is your feature request related to a problem? Please describe.**
I run the demo code and find the `models` and `predictions` are the same.

![image](https://user-images.githubusercontent.com/19947331/109747933-f664f880-7c12-11eb-87c3-3d17c07eb593.png)

**Describe the solution you'd like**

How can I get the per case predictions?

Kindest regards,
Jun

**Comment by shankarpandala** [comment]
@JunMa11 This feature is already available. You just need use predictions = True in the LazyRegressor or LazyClassifier.

**Comment by JunMa11** [comment]
Hi @shankarpandala ,

Got it.

Thanks for your reply very much:)

Best,
Jun
