### ISSUE TITLE
'ColumnTransformer' object has no attribute '_check_n_features'

### ISSUE THREAD

**Issue by ManuFU** [shankarpandala/lazypredict#339]
**Describe the bug**
When fitting the LazyRegressor, i get following output for all algorithms.

![image](https://user-images.githubusercontent.com/15906404/112719208-0614eb80-8ef8-11eb-9abd-e080ae0be6b4.png)

**To Reproduce**
Check out this notebook
https://colab.research.google.com/drive/1CZa8rL2N4PxUqhCKAyzO3incPFfGwwIM?usp=sharing

**Expected behavior**
I expect the table of the results of the regressors

**Comment by brendalf** [comment]
Hi @ManuFU, thank you for opening this issue.
@shankarpandala, when the input doesn't have categorical features, the categorical_low and categorical_high column transformers are useless. Perhaps this is causing the issue?

Doing some research, I've found that this issue can also be related to sklearn versions conflict. But looking at the notebook, I didn't find any.
