### ISSUE TITLE
incompatiable with Scikit-learn V0.24.2

### ISSUE THREAD

**Issue by kgmat** [shankarpandala/lazypredict#351]
Hello,

Facing this issue. 
   
**lazypredict 0.2.9 requires scikit-learn==0.23.1, but you have scikit-learn 0.24.2 which is incompatible.**

lazypredict has to be restricted to scikit older version?

thanks

**Comment by parayamelo** [comment]
Same here, scikit-learn is already in version 1.0, there is no foreseable change?
