### ISSUE TITLE
Update pandas version

### ISSUE THREAD

**Issue by davidegazze** [shankarpandala/lazypredict#353]
From the requirement file, I see that the pandas version required is pandas==1.0.5

Do you think that it could be possible to use a newer one?

**Comment by this-josh** [comment]
I too am finding this a limiting factor.

**Comment by slackline** [comment]
Similarly for packages such as `scipy`, `numpy`, `scikit-learn`, `tqdm` etc. If most other requirements could be un-pegged to specific versions that would be really useful.

**Comment by shankarpandala** [comment]
Will be done soon in next release

**Comment by slackline** [comment]
Brilliant, thank you :clap:
