### ISSUE TITLE
ValueError: ('_SigmoidCalibration', <class 'sklearn.calibration._SigmoidCalibration'>) is not in list

### ISSUE THREAD

**Issue by balazsgonczy** [shankarpandala/lazypredict#365]
**Describe the bug**
The bug occurs when trying to import the "1 from lazypredict.Supervised import LazyClassifier" line, which causes the "REGRESSORS.pop(REGRESSORS.index(i))" line to crash.

**Code to run:**

from lazypredict.Supervised import LazyClassifier
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split

data = load_breast_cancer()
X = data.data
y= data.target

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=.5,random_state =123)

clf = LazyClassifier(verbose=0,ignore_warnings=True, custom_metric=None)
models,predictions = clf.fit(X_train, X_test, y_train, y_test)

print(models)

**Comment by hsbehera** [comment]
Same error occured

**Comment by balazsgonczy** [comment]
I don't know what caused it but Google Collab's stable environment handles the dependency import smoothly. So I recommend running the workflow in that environment.
