### ISSUE TITLE
TypeError (OneHotEncoder) on importing LazyRegressor from lazypredict.Supervised

### ISSUE THREAD

**Issue by ehsanyousefzadehasl** [shankarpandala/lazypredict#441]
The following error appears on "from lazypredict.Supervised import LazyRegressor"

 File "<stdin>", line 1, in <module>
 File "C:\Users\ ... \Python312\site-packages\lazypredict\Supervised.py", line 98, in <module>
   ("encoding", OneHotEncoder(handle_unknown="ignore", sparse=False)),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: OneHotEncoder.__init__() got an unexpected keyword argument 'sparse'

Python version: 3.12.1
OS: windows 10

**Comment by JSchoeck** [comment]
The keyword changed to `sparse_output`.

**Comment by ehsanyousefzadehasl** [comment]
Tested and it worked without the issue. Closed this issue.
