### ISSUE TITLE
Include Adjusted R-square metric for regression

### ISSUE THREAD

**Issue by shankarpandala** [shankarpandala/lazypredict#63]
**Is your feature request related to a problem? Please describe.**
R-square is not a correct metric when we have multiple features

**Describe the solution you'd like**
Adjusted R-square metric needs to be included for Regression

**Comment by brendalf** [comment]
What do you have in mind? Replace the r-squared with adjusted r-squared or leave both?

**Comment by shankarpandala** [comment]
I will include it in the next release. 
If you want work on it. Please go ahead and raise a PR

**Comment by brendalf** [comment]
Ok, I will get it done.
