### ISSUE TITLE
running problem

### ISSUE THREAD

**Issue by pavansai26** [shankarpandala/lazypredict#97]
**Describe the bug**
catboost is not installing and it shows sys is not defined
 module not found error is coming

**Comment by shankarpandala** [comment]
Try `import sys` before your code
This is designed to use catboost only if it is already installed. If it is not installed it will ignore. Will look into the issue and fix it in next release

**Comment by rrupam** [comment]
I have the same problem. I have 
`import sys` 
before the code, but the error persists.

**Comment by Branden-Kang** [comment]
I have the same problem but I solved it. Before running the "lazy predict" code, you should install catboost first. So, use this code to install catboost: !pip3 install catboost and then you can run the code "from lazypredict.Supervised import LazyClassifier".

**Comment by Vipul-15** [comment]
I installed catboost now, but the error still persists ( sys not defined) while I try to import using ---
from lazypredict.Supervised import LazyClassifier

**Comment by shankarpandala** [comment]
@rrupam @Branden-Kang @Vipul-15 
Install 'xgboost', 'catboost', 'lightgbm' before using lazypredict and let me know if this error still exists

**Comment by Branden-Kang** [comment]
Yes. I fixed it. You need to install 'xgboost', 'catboost', 'lightgbm'. But, you have to remember that use pip3!!

**Comment by Vipul-15** [comment]
Yes @shankarpandala . I didn't had lightgbm, installed it. Now error is gone. 😃

**Comment by shankarpandala** [comment]
@pavansai26 you can also install xgboost lightgbm and catboost for time being I will fix this sys issue soon.

**Comment by guhan93** [comment]
when i run the regression code i get only the learning rates

**Comment by guhan93** [comment]
having errors in stacking regressor

**Comment by shankarpandala** [comment]
@rrupam @Branden-Kang @Vipul-15 @pavansai26 

This issue is fixed in new patch and removed catboost

@guhan93 Please raise a new issue for it with details

**Comment by guhan93** [comment]
![image](https://user-images.githubusercontent.com/47147736/87042711-a82d6000-c211-11ea-8d2b-9a8ff2743f0b.png)

**Comment by guhan93** [comment]
solve this

**Comment by guhan93** [comment]
![image](https://user-images.githubusercontent.com/47147736/87043115-3acdff00-c212-11ea-83d2-a6dc5b570b1b.png)
